apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: supertest
  name: supertest
  namespace: default
spec:
  containers:
  - image: nginx
    name: supertest
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
